backend:
  name: git-gateway
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: reference
    label: Reference
    folder: data/references
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
